# Generated by Django 5.2.2 on 2025-06-12 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_record',
            },
        ),
        migrations.CreateModel(
            name='TotalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedestrian', models.IntegerField(default=0)),
                ('car', models.IntegerField(default=0)),
                ('bus', models.IntegerField(default=0)),
                ('truck', models.IntegerField(default=0)),
                ('two_wheeler', models.IntegerField(default=0)),
                ('traffic_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_counts', to='core.trafficrecord')),
            ],
            options={
                'db_table': 'total_count',
            },
        ),
    ]
