# Generated by Django 5.2.2 on 2025-06-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalcount',
            options={'ordering': ['-traffic_record__timestamp']},
        ),
        migrations.AlterModelOptions(
            name='trafficrecord',
            options={'ordering': ['-timestamp']},
        ),
    ]
